spring:
  application:
    name: msextratobancario

  #RabbitMQ
  rabbitmq:
    host: ${RABBITMQ_SERVER:localhost}
    port: 5672
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/dbbanco?useSSL=false&serverTimezone=UTC}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:1234}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

#Queue
mq:
  queues:
    transacao-banco: transacao-banco

